CREATE TABLE articulo (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY , 
     referencia VARCHAR (20) NOT NULL , 
     color VARCHAR (10) NOT NULL , 
     material VARCHAR (10) NOT NULL , 
     descripcion VARCHAR (30) NOT NULL , 
     precioUnitario INTEGER NOT NULL , 
     cantidad INTEGER NOT NULL , 
     Ventas_id INTEGER NOT NULL
);

ALTER TABLE articulo ADD CONSTRAINT articulo_pk PRIMARY KEY ( id );

CREATE TABLE clientes (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY , 
     nombre VARCHAR (20) NOT NULL , 
     identificador INTEGER NOT NULL , 
     estadoCliente VARCHAR(10) NOT NULL 
);

ALTER TABLE clientes ADD CONSTRAINT clientes_pk PRIMARY KEY ( id );

CREATE TABLE ventas (
    id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    codigo             INTEGER NOT NULL,
    nombre             CHAR(20) NOT NULL,
    apellido           CHAR(20),
    telefono           CHAR(20),
    correoelectronico  CHAR(20),
    cursos_id          INTEGER NOT NULL
);

ALTER TABLE ventas ADD CONSTRAINT ventas_pk PRIMARY KEY ( id);



ALTER TABLE articulo
    ADD CONSTRAINT articulo_ventas_fk FOREIGN KEY ( ventas_id )
        REFERENCES ventas ( id );

ALTER TABLE ventas
    ADD CONSTRAINT ventas_clientes_fk FOREIGN KEY ( clientes_id )
        REFERENCES clientes ( id );
